name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm ci

      - name: Debug Node environment
        run: |
          echo "Node version:"
          node -v
          echo "Node path:"
          which node
          echo "Vitest version:"
          npx vitest --version

      - name: Run tests
        run: npm run test -- --coverage
